version: "3.9"
services: 
  postgres_postgis:
    image: postgis/postgis
    container_name: postgres_postgis
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATA: ${POSTGRES_DATA}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - crm_network

  adminer_pgadmin4:
    image: dpage/pgadmin4
    container_name: adminer_pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8090:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - crm_network

  crm-aqua-kinetics-back-dev:
    build: ./ 
    container_name: crm-aqua-kinetics-back-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${DEV_PORT}:${DEV_PORT}
    depends_on:
      - postgres_postgis
    environment:
      - PORT=${DEV_PORT}
      - SECRET=${SECRET}
      - IS_DEV=true
      - IS_LOCAL=false
    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm i -g @nestjs/cli; npm install --force; npm run start:dev"
    networks:
      - crm_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  crm_network:
    driver: bridge